# SPDX-License-Identifier: Apache-2.0

filegroup(
    name = "all_inputs",
    srcs = glob([
        "testdata/*.cue",
    ]) + [
        "//com/deployment/profiles:all_profiles",
        "//com/deployment/schema:deployment.cue",
    ],
    visibility = ["//visibility:public"],
)

exports_files(glob(["testdata/*.cue"]))
