# SPDX-License-Identifier: Apache-2.0

package(default_visibility = ["//visibility:public"])

exports_files([
    "LICENSE",
    "__init__.py",
    "Cargo.Bazel.lock",
    "cargo-bazel-lock.json",
])

alias(
    name = "com",
    actual = "//com:runtime",
)

alias(
    name = "exec",
    actual = "//exec:model",
)

test_suite(
    name = "all_tests",
    tests = [
        "//codegen:rustfmt_test",
        "//com/tests:all_tests",
        "//crypto/tests:all_tests",
        "//exec/tests:all_tests",
        "//log/tests:all_tests",
        "//per/tests:all_tests",
    ],
)
