# SPDX-License-Identifier: Apache-2.0

load("//bazel:application.bzl", "ovf_cc_application")

ovf_cc_application(
    name = "driving_policy",
    srcs = ["main.cpp"],
    deployment = "deployment.cue",
    interfaces = ["//examples/sensor_fusion/interface:environment_model"],
    logging = True,
    persistent_schemas = ["//examples/driving_policy/persistence:policy_state"],
    tags = ["manual"],
    visibility = ["//visibility:public"],
)
