# SPDX-License-Identifier: Apache-2.0

load("//bazel:application.bzl", "ovf_cc_application")

package(default_visibility = ["//visibility:public"])

ovf_cc_application(
    name = "radar_service",
    srcs = ["service/main.cpp"],
    deployment = "deployments/vsomeip/service.json",
    idl = ["//contracts/radar:radar.smithy"],
    tags = ["manual"],
    target_compatible_with = ["@platforms//os:linux"],
)

ovf_cc_application(
    name = "radar_iceoryx2_service",
    srcs = ["service/main.cpp"],
    deployment = "deployments/iceoryx2/service.json",
    deployment_namespace = "radar_service_deployment",
    idl = ["//contracts/radar:radar.smithy"],
    tags = ["manual"],
)

ovf_cc_application(
    name = "radar_iceoryx2_client",
    srcs = ["client/main.cpp"],
    deployment = "deployments/iceoryx2/client.json",
    deployment_namespace = "radar_client_deployment",
    idl = ["//contracts/radar:radar.smithy"],
    tags = ["manual"],
)

ovf_cc_application(
    name = "radar_client",
    srcs = ["client/main.cpp"],
    deployment = "deployments/vsomeip/client.json",
    idl = ["//contracts/radar:radar.smithy"],
    tags = ["manual"],
    target_compatible_with = ["@platforms//os:linux"],
)
