# SPDX-License-Identifier: Apache-2.0

load("//bazel:application.bzl", "ovf_cc_application")

package(default_visibility = ["//visibility:public"])

ovf_cc_application(
    name = "radar_inproc_client",
    srcs = ["client/main.cpp"],
    deployment = "client/ipc-deployment.cue",
    interfaces = ["//contracts/radar"],
    platform = "//platform:inproc",
    tags = ["manual"],
    deps = ["//exec:application_api"],
)

ovf_cc_application(
    name = "radar_service",
    srcs = ["service/main.cpp"],
    deployment = "service/deployment.cue",
    interfaces = ["//contracts/radar"],
    platform = "//platform:vsomeip",
    tags = ["manual"],
    target_compatible_with = ["@platforms//os:linux"],
    deps = ["//exec:application_api"],
)

ovf_cc_application(
    name = "radar_iceoryx2_service",
    srcs = ["service/main.cpp"],
    deployment = "service/ipc-deployment.cue",
    interfaces = ["//contracts/radar"],
    platform = "//platform:iceoryx2",
    tags = ["manual"],
    deps = ["//exec:application_api"],
)

ovf_cc_application(
    name = "radar_iceoryx2_client",
    srcs = ["client/main.cpp"],
    deployment = "client/ipc-deployment.cue",
    interfaces = ["//contracts/radar"],
    platform = "//platform:iceoryx2",
    tags = ["manual"],
    deps = ["//exec:application_api"],
)

ovf_cc_application(
    name = "radar_client",
    srcs = ["client/main.cpp"],
    deployment = "client/deployment.cue",
    interfaces = ["//contracts/radar"],
    platform = "//platform:vsomeip",
    tags = ["manual"],
    target_compatible_with = ["@platforms//os:linux"],
    deps = ["//exec:application_api"],
)
