# SPDX-License-Identifier: Apache-2.0

load("//bazel:application.bzl", "ovf_cc_application")

package(default_visibility = ["//visibility:public"])

ovf_cc_application(
    name = "radar_app",
    srcs = ["main.cpp"],
    hdrs = ["radar_logic.hpp"],
    deployment = "//com/deployment:examples/radar-inproc.json",
    idl = ["//contracts/radar:radar.smithy"],
)
