#pragma once

// SPDX-License-Identifier: Apache-2.0
// Generated by ovf_codegen; do not edit.

#include <array>
#include <cstddef>
#include <cstdint>
#include <optional>
#include <span>
#include <string>
#include <variant>
#include <vector>

#include "ovf/com/generated.hpp"

namespace test::empty {


} // namespace test::empty

namespace ovf::com {

} // namespace ovf::com

namespace test::empty {


} // namespace test::empty
