# SPDX-License-Identifier: Apache-2.0

load("@openvehicleframework//bazel:application.bzl", "ovf_cc_application")

ovf_cc_application(
    name = "separate_radar_app",
    srcs = ["main.cpp"],
    deployment = "@openvehicleframework//examples/radar:client/ipc-deployment.cue",
    interfaces = ["@openvehicleframework//contracts/radar"],
)
