# SPDX-License-Identifier: Apache-2.0

load("@openvehicleframework//bazel:application.bzl", "ovf_cc_application")

ovf_cc_application(
    name = "separate_radar_app",
    srcs = ["main.cpp"],
    deployment = "@openvehicleframework//examples/radar:client/deployment.cue",
    idl = ["@openvehicleframework//contracts/radar:radar.smithy"],
    platform = "@openvehicleframework//platform:providers/inproc.cue",
)
